-- CUSTOM TYPE ENUMS
CREATE TYPE public.estado_asistencia AS ENUM ('puntual', 'retardo', 'falta', 'salida_puntual', 'salida_temprano', 'retardo_a', 'retardo_b', 'falta_por_retardo', 'salida_no_cumplida');
CREATE TYPE public.regimen_laboral_enum AS ENUM ('base', 'eventual');
CREATE TYPE public.tipo_asistencia AS ENUM ('entrada', 'salida');
CREATE TYPE public.tipo_biometrico AS ENUM ('facial', 'dactilar');
CREATE TYPE public.tipo_dispositivo AS ENUM ('movil', 'escritorio');
CREATE TYPE public.tipo_dispositivo_origen AS ENUM ('movil', 'escritorio', 'manual', 'sistema');
CREATE TYPE public.tipo_estado_asistencia AS ENUM ('puntual', 'retardo');
CREATE TYPE public.tipo_estado_biometrico AS ENUM ('conectado', 'desconectado', 'error');
CREATE TYPE public.tipo_estado_cuenta AS ENUM ('activo', 'suspendido', 'baja', 'bloqueado');
CREATE TYPE public.tipo_estado_incidencia AS ENUM ('aprobado', 'rechazado', 'pendiente');
CREATE TYPE public.tipo_estado_solicitud AS ENUM ('pendiente', 'aceptado', 'rechazado');
CREATE TYPE public.tipo_evento AS ENUM ('asistencia', 'incidencia', 'aviso', 'alerta', 'justificacion', 'permiso', 'sancion', 'reconocimiento', 'sistema', 'usuario', 'rol', 'autenticacion', 'empleado', 'departamento', 'horario', 'credencial', 'solicitud', 'dispositivo', 'asistencia_manual');
CREATE TYPE public.tipo_formato_fecha AS ENUM ('DD/MM/YYYY', 'MM/DD/YYYY', 'YYYY/MM/DD');
CREATE TYPE public.tipo_formato_hora AS ENUM ('12', '24');
CREATE TYPE public.tipo_idioma AS ENUM ('es', 'en');
CREATE TYPE public.tipo_incidencia AS ENUM ('retardo', 'justificante', 'permiso', 'vacaciones', 'festivo');
CREATE TYPE public.tipo_prioridad AS ENUM ('alta', 'media', 'baja', 'critica');

-- DATABASE CREATION SCRIPT GENERATED BY ANTIGRAVITY
-- CONNECTED TO DATABASE: checador-fas

-- SEQUENCES
CREATE SEQUENCE IF NOT EXISTS seq_usuarios START 1;
CREATE SEQUENCE IF NOT EXISTS seq_empleados START 1;
CREATE SEQUENCE IF NOT EXISTS seq_roles START 1;
CREATE SEQUENCE IF NOT EXISTS seq_departamentos START 1;
CREATE SEQUENCE IF NOT EXISTS seq_horarios START 1;
CREATE SEQUENCE IF NOT EXISTS seq_tolerancias START 1;
CREATE SEQUENCE IF NOT EXISTS seq_asistencias START 1;
CREATE SEQUENCE IF NOT EXISTS seq_incidencias START 1;
CREATE SEQUENCE IF NOT EXISTS seq_credenciales START 1;
CREATE SEQUENCE IF NOT EXISTS seq_escritorio START 1;
CREATE SEQUENCE IF NOT EXISTS seq_movil START 1;
CREATE SEQUENCE IF NOT EXISTS seq_biometrico START 1;
CREATE SEQUENCE IF NOT EXISTS seq_solicitudes START 1;
CREATE SEQUENCE IF NOT EXISTS seq_eventos START 1;
CREATE SEQUENCE IF NOT EXISTS seq_configuraciones START 1;
CREATE SEQUENCE IF NOT EXISTS seq_empresas START 1;
CREATE SEQUENCE IF NOT EXISTS seq_modulos START 1;
CREATE SEQUENCE IF NOT EXISTS seq_permisos START 1;
CREATE SEQUENCE IF NOT EXISTS seq_usuarios_roles START 1;
CREATE SEQUENCE IF NOT EXISTS seq_empleados_departamentos START 1;
CREATE SEQUENCE IF NOT EXISTS seq_auditoria START 1;
CREATE SEQUENCE IF NOT EXISTS seq_dias_festivos START 1;
CREATE SEQUENCE IF NOT EXISTS seq_avisos START 1;
CREATE SEQUENCE IF NOT EXISTS seq_avisos_empleados START 1;
CREATE SEQUENCE IF NOT EXISTS seq_system_logs START 1;


-- GENERATED ON: 2026-06-03T03:22:32.863Z


-- Table: asistencias
CREATE TABLE public."asistencias" (
    "id" VARCHAR(55) NOT NULL,
    "estado" VARCHAR(50) NOT NULL DEFAULT 'puntual'::estado_asistencia,
    "dispositivo_origen" tipo_dispositivo_origen NOT NULL,
    "ubicacion" TEXT[],
    "fecha_registro" TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "empleado_id" VARCHAR(55) NOT NULL,
    "tipo" tipo_asistencia NOT NULL DEFAULT 'entrada'::tipo_asistencia,
    "departamento_id" VARCHAR(55),
    "empresa_id" VARCHAR(55),
    "alertas" JSONB DEFAULT '[]'::jsonb,
    "horario_snapshot" JSONB,
    "horario_id" VARCHAR(50),
    CONSTRAINT "asistencias_pkey" PRIMARY KEY (id)
);

CREATE INDEX idx_asistencias_empleado ON public.asistencias USING btree (empleado_id);
CREATE INDEX idx_asistencias_fecha ON public.asistencias USING btree (fecha_registro);
CREATE INDEX idx_asistencias_horario_id ON public.asistencias USING btree (horario_id);
CREATE INDEX idx_asistencias_estado ON public.asistencias USING btree (estado);


-- Table: avisos
CREATE TABLE public."avisos" (
    "id" VARCHAR(50) NOT NULL,
    "titulo" VARCHAR(255) NOT NULL,
    "contenido" TEXT,
    "es_global" BOOLEAN NOT NULL DEFAULT false,
    "fecha_registro" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "creado_por" VARCHAR(50),
    "empresa_id" VARCHAR(55),
    CONSTRAINT "avisos_pkey" PRIMARY KEY (id)
);

CREATE INDEX idx_avisos_es_global ON public.avisos USING btree (es_global);
CREATE INDEX idx_avisos_fecha_registro ON public.avisos USING btree (fecha_registro DESC);


-- Table: avisos_empleados
CREATE TABLE public."avisos_empleados" (
    "id" VARCHAR(55) NOT NULL,
    "empleado_id" VARCHAR(55) NOT NULL,
    "aviso_id" VARCHAR(50) NOT NULL,
    "fecha_registro" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "avisos_empleados_pkey" PRIMARY KEY (id),
    CONSTRAINT "uk_avisos_empleados_empleado_aviso" UNIQUE (empleado_id, aviso_id)
);

CREATE INDEX idx_avisos_empleados_empleado ON public.avisos_empleados USING btree (empleado_id);
CREATE INDEX idx_avisos_empleados_fecha ON public.avisos_empleados USING btree (fecha_registro DESC);
CREATE INDEX idx_avisos_empleados_aviso ON public.avisos_empleados USING btree (aviso_id);


-- Table: biometrico
CREATE TABLE public."biometrico" (
    "id" VARCHAR(55) NOT NULL,
    "nombre" VARCHAR(55) NOT NULL,
    "descripcion" TEXT,
    "tipo" tipo_biometrico NOT NULL,
    "puerto" VARCHAR(55),
    "ip" VARCHAR(15),
    "estado" tipo_estado_biometrico DEFAULT 'desconectado'::tipo_estado_biometrico,
    "es_activo" BOOLEAN DEFAULT true,
    "escritorio_id" VARCHAR(55),
    "device_id" VARCHAR(255),
    CONSTRAINT "biometrico_pkey" PRIMARY KEY (id)
);

CREATE INDEX idx_biometrico_escritorio ON public.biometrico USING btree (escritorio_id);
CREATE INDEX idx_biometrico_estado ON public.biometrico USING btree (estado);


-- Table: configuraciones
CREATE TABLE public."configuraciones" (
    "id" VARCHAR(55) NOT NULL,
    "idioma" tipo_idioma DEFAULT 'es'::tipo_idioma,
    "es_mantenimiento" BOOLEAN DEFAULT false,
    "formato_fecha" tipo_formato_fecha DEFAULT 'DD/MM/YYYY'::tipo_formato_fecha,
    "formato_hora" tipo_formato_hora DEFAULT '24'::tipo_formato_hora,
    "zona_horaria" VARCHAR(50) DEFAULT 'America/Mexico_City'::character varying,
    "paleta_colores" JSON,
    "intentos_maximos" INTEGER DEFAULT 3,
    "orden_credenciales" JSON,
    "segmentos_red" JSONB DEFAULT '[]'::jsonb,
    "tolerancia_id" VARCHAR,
    "intervalo_bloques_minutos" INTEGER DEFAULT 60,
    "requiere_salida" BOOLEAN DEFAULT true,
    "cooldown_bloqueo" INTEGER DEFAULT 1800,
    "omision_red_activa" BOOLEAN DEFAULT false,
    "omision_red_empleados" JSONB DEFAULT '[]'::jsonb,
    "omision_gps_activa" BOOLEAN DEFAULT false,
    "omision_gps_empleados" JSONB DEFAULT '[]'::jsonb,
    CONSTRAINT "configuraciones_pkey" PRIMARY KEY (id)
);



-- Table: configuraciones_escritorio
CREATE TABLE public."configuraciones_escritorio" (
    "id" VARCHAR(100) NOT NULL,
    "configuracion_id" VARCHAR(100) NOT NULL,
    "escritorio_id" VARCHAR(100) NOT NULL,
    "sincronizacion_automatica" BOOLEAN DEFAULT true,
    "frecuencia_sincronizacion_min" INTEGER DEFAULT 15,
    "modo_offline_permitido" BOOLEAN DEFAULT true,
    "iniciar_con_windows" BOOLEAN DEFAULT false,
    "metodos_autenticacion" JSONB DEFAULT '{"codigo": true, "huella": true, "rostro": true}'::jsonb,
    "es_activo" BOOLEAN DEFAULT true,
    "creado_en" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "actualizado_en" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "prioridad_biometrico" JSONB DEFAULT '[{"nivel": 1, "activo": true, "metodo": "huella"}, {"nivel": 2, "activo": true, "metodo": "rostro"}, {"nivel": 3, "activo": true, "metodo": "codigo"}]'::jsonb,
    "es_mantenimiento" BOOLEAN DEFAULT false,
    CONSTRAINT "configuraciones_escritorio_pkey" PRIMARY KEY (id)
);



-- Table: credenciales
CREATE TABLE public."credenciales" (
    "id" VARCHAR(55) NOT NULL,
    "dactilar" BYTEA,
    "facial" BYTEA,
    "pin" VARCHAR(6),
    "fecha_registro" TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "empleado_id" VARCHAR(55) NOT NULL,
    CONSTRAINT "credenciales_pkey" PRIMARY KEY (id)
);



-- Table: departamentos
CREATE TABLE public."departamentos" (
    "id" VARCHAR(55) NOT NULL,
    "nombre" VARCHAR(55) NOT NULL,
    "descripcion" TEXT,
    "fecha_registro" TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "es_activo" BOOLEAN DEFAULT true,
    "color" VARCHAR(6),
    "ubicacion" JSONB,
    "jefes" TEXT[],
    "empresa_id" VARCHAR(55),
    CONSTRAINT "departamentos_pkey" PRIMARY KEY (id),
    CONSTRAINT "departamentos_nombre_empresa_unique" UNIQUE (nombre, empresa_id)
);



-- Table: dias_festivos
CREATE TABLE public."dias_festivos" (
    "id" VARCHAR(55) NOT NULL,
    "nombre" VARCHAR(100) NOT NULL,
    "fecha" DATE NOT NULL,
    "es_obligatorio" BOOLEAN DEFAULT true,
    "tipo" VARCHAR(20) DEFAULT 'oficial'::character varying,
    "pais" VARCHAR(3) DEFAULT 'MEX'::character varying,
    "estado" VARCHAR(50),
    "descripcion" TEXT,
    "fecha_registro" TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "es_activo" BOOLEAN DEFAULT true,
    "empresa_id" VARCHAR(55),
    CONSTRAINT "dias_festivos_pkey" PRIMARY KEY (id),
    CONSTRAINT "dias_festivos_fecha_key" UNIQUE (fecha)
);

CREATE INDEX idx_dias_festivos_fecha ON public.dias_festivos USING btree (fecha);
CREATE INDEX idx_dias_festivos_tipo ON public.dias_festivos USING btree (tipo);
CREATE INDEX idx_dias_festivos_activo ON public.dias_festivos USING btree (es_activo);


-- Table: empleados
CREATE TABLE public."empleados" (
    "id" VARCHAR(55) NOT NULL,
    "rfc" VARCHAR(17),
    "nss" VARCHAR(17),
    "fecha_registro" TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "horario_id" VARCHAR(55),
    "usuario_id" VARCHAR(55),
    "regimen_laboral" regimen_laboral_enum NOT NULL DEFAULT 'base'::regimen_laboral_enum,
    "contadores" JSONB DEFAULT '{}'::jsonb,
    CONSTRAINT "empleados_pkey" PRIMARY KEY (id)
);

CREATE INDEX idx_empleados_horario ON public.empleados USING btree (horario_id);
CREATE INDEX idx_empleados_usuario ON public.empleados USING btree (usuario_id);


-- Table: empleados_departamentos
CREATE TABLE public."empleados_departamentos" (
    "id" VARCHAR(55) NOT NULL,
    "fecha_registro" TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "es_activo" BOOLEAN DEFAULT true,
    "empleado_id" VARCHAR(55) NOT NULL,
    "departamento_id" VARCHAR(55) NOT NULL,
    CONSTRAINT "empleados_departamentos_pkey" PRIMARY KEY (id)
);

CREATE INDEX idx_empleados_departamentos_empleado ON public.empleados_departamentos USING btree (empleado_id);
CREATE INDEX idx_empleados_departamentos_departamento ON public.empleados_departamentos USING btree (departamento_id);
CREATE INDEX idx_empleados_departamentos_activo ON public.empleados_departamentos USING btree (es_activo);


-- Table: empresas
CREATE TABLE public."empresas" (
    "id" VARCHAR(55) NOT NULL,
    "nombre" VARCHAR(55) NOT NULL,
    "logo" TEXT,
    "es_activo" BOOLEAN DEFAULT true,
    "fecha_registro" TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "configuracion_id" VARCHAR(55),
    "telefono" VARCHAR(50),
    "correo" VARCHAR(255),
    "limite_empleados" INTEGER,
    "limite_dispositivos" INTEGER,
    "fecha_vencimiento" DATE,
    "prefijo" VARCHAR(3),
    "identificador" VARCHAR(100),
    "motor_asistencias" VARCHAR(50) DEFAULT 'dinamico'::character varying,
    "configuracion_reportes" JSONB DEFAULT '{"fuente": "Helvetica", "encabezado": {"color_fondo": "#ffffff", "color_texto": "#000000", "mostrar_logo": true, "texto_derecho": "", "texto_izquierdo": ""}, "pie_pagina": {"color_texto": "#666666", "texto_central": "", "mostrar_numeracion": true}}'::jsonb,
    "tipo_institucion" VARCHAR(30) DEFAULT 'corporativa'::character varying,
    CONSTRAINT "empresas_pkey" PRIMARY KEY (id),
    CONSTRAINT "empresas_identificador_key" UNIQUE (identificador),
    CONSTRAINT "unique_prefijo" UNIQUE (prefijo) DEFERRABLE INITIALLY DEFERRED
);



-- Table: escritorio
CREATE TABLE public."escritorio" (
    "id" VARCHAR(55) NOT NULL,
    "nombre" VARCHAR(55) NOT NULL,
    "descripcion" TEXT,
    "ip" TEXT,
    "mac" TEXT,
    "sistema_operativo" TEXT,
    "dispositivos_biometricos" JSON,
    "es_activo" BOOLEAN DEFAULT true,
    "empresa_id" VARCHAR(55),
    "comando_kiosko" VARCHAR(50) DEFAULT 'none'::character varying,
    "comando_watchdog" VARCHAR(50) DEFAULT 'none'::character varying,
    "ultimo_visto" TIMESTAMP WITH TIME ZONE,
    CONSTRAINT "escritorio_pkey" PRIMARY KEY (id)
);



-- Table: eventos
CREATE TABLE public."eventos" (
    "id" VARCHAR(55) NOT NULL,
    "titulo" VARCHAR(100) NOT NULL,
    "descripcion" TEXT,
    "tipo_evento" tipo_evento NOT NULL,
    "prioridad" tipo_prioridad DEFAULT 'media'::tipo_prioridad,
    "detalles" JSON,
    "fecha_registro" TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "empleado_id" VARCHAR(55),
    "empresa_id" VARCHAR(55),
    CONSTRAINT "eventos_pkey" PRIMARY KEY (id)
);

CREATE INDEX idx_eventos_empleado ON public.eventos USING btree (empleado_id);
CREATE INDEX idx_eventos_tipo ON public.eventos USING btree (tipo_evento);
CREATE INDEX idx_eventos_fecha ON public.eventos USING btree (fecha_registro);


-- Table: horarios
CREATE TABLE public."horarios" (
    "id" VARCHAR(55) NOT NULL,
    "fecha_inicio" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    "fecha_fin" TIMESTAMP WITHOUT TIME ZONE,
    "configuracion" JSON NOT NULL,
    "es_activo" BOOLEAN DEFAULT true,
    "empresa_id" VARCHAR(55),
    CONSTRAINT "horarios_pkey" PRIMARY KEY (id)
);



-- Table: incidencias
CREATE TABLE public."incidencias" (
    "id" VARCHAR(55) NOT NULL,
    "motivo" TEXT,
    "tipo" tipo_incidencia NOT NULL,
    "observaciones" TEXT,
    "fecha_inicio" TIMESTAMP WITHOUT TIME ZONE,
    "fecha_fin" TIMESTAMP WITHOUT TIME ZONE,
    "estado" tipo_estado_incidencia DEFAULT 'pendiente'::tipo_estado_incidencia,
    "empleado_id" VARCHAR(55) NOT NULL,
    "empresa_id" VARCHAR(55),
    CONSTRAINT "incidencias_pkey" PRIMARY KEY (id)
);

CREATE INDEX idx_incidencias_empleado ON public.incidencias USING btree (empleado_id);
CREATE INDEX idx_incidencias_estado ON public.incidencias USING btree (estado);
CREATE INDEX idx_incidencias_tipo ON public.incidencias USING btree (tipo);


-- Table: movil
CREATE TABLE public."movil" (
    "id" VARCHAR(55) NOT NULL,
    "sistema_operativo" TEXT,
    "es_root" BOOLEAN DEFAULT false,
    "es_activo" BOOLEAN DEFAULT true,
    "fecha_registro" TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "empleado_id" VARCHAR(55) NOT NULL,
    "ip" TEXT,
    "mac" TEXT,
    "empresa_id" VARCHAR(55),
    CONSTRAINT "movil_pkey" PRIMARY KEY (id)
);



-- Table: permisos_auditoria
CREATE TABLE public."permisos_auditoria" (
    "id" VARCHAR(55) NOT NULL,
    "permisos_anteriores" BIGINT,
    "permisos_nuevos" BIGINT,
    "motivo" TEXT,
    "cambios_detalle" JSON,
    "fecha_modificacion" TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "rol_id" VARCHAR(55) NOT NULL,
    "usuario_modificador_id" VARCHAR(55) NOT NULL,
    CONSTRAINT "permisos_auditoria_pkey" PRIMARY KEY (id)
);

CREATE INDEX idx_permisos_auditoria_rol ON public.permisos_auditoria USING btree (rol_id);
CREATE INDEX idx_permisos_auditoria_fecha ON public.permisos_auditoria USING btree (fecha_modificacion);


-- Table: roles
CREATE TABLE public."roles" (
    "id" VARCHAR(55) NOT NULL,
    "nombre" VARCHAR(55) NOT NULL,
    "descripcion" TEXT,
    "posicion" INTEGER DEFAULT 1,
    "permisos_bitwise" BIGINT DEFAULT 0,
    "es_admin" BOOLEAN DEFAULT false,
    "es_empleado" BOOLEAN DEFAULT false,
    "fecha_registro" TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "tolerancia_id" VARCHAR(55),
    "color" VARCHAR(7),
    "es_activo" BOOLEAN DEFAULT true,
    "empresa_id" VARCHAR(55),
    CONSTRAINT "chk_permisos_positivo" CHECK ((permisos_bitwise >= 0)),
    CONSTRAINT "roles_pkey" PRIMARY KEY (id)
);

CREATE INDEX idx_roles_posicion ON public.roles USING btree (posicion);
CREATE INDEX idx_roles_es_admin ON public.roles USING btree (es_admin);


-- Table: sesiones_movil
CREATE TABLE public."sesiones_movil" (
    "id" SERIAL NOT NULL,
    "usuario_id" VARCHAR(55),
    "empleado_id" VARCHAR(55),
    "tipo" VARCHAR(10) NOT NULL,
    "modo" VARCHAR(20) NOT NULL DEFAULT 'offline'::character varying,
    "fecha_evento" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    "dispositivo" VARCHAR(50) DEFAULT 'movil'::character varying,
    "recibido_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
    CONSTRAINT "sesiones_movil_pkey" PRIMARY KEY (id)
);



-- Table: solicitudes
CREATE TABLE public."solicitudes" (
    "id" VARCHAR(55) NOT NULL,
    "tipo" tipo_dispositivo NOT NULL,
    "nombre" VARCHAR(55) NOT NULL,
    "descripcion" TEXT,
    "correo" VARCHAR(55),
    "ip" TEXT,
    "mac" TEXT,
    "sistema_operativo" VARCHAR(55),
    "estado" tipo_estado_solicitud DEFAULT 'pendiente'::tipo_estado_solicitud,
    "fecha_registro" TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "fecha_respuesta" TIMESTAMP WITHOUT TIME ZONE,
    "observaciones" TEXT,
    "token" VARCHAR(6) NOT NULL,
    "empresa_id" VARCHAR(55),
    "dispositivos_temp" JSON,
    "advertencia_red" BOOLEAN DEFAULT false,
    CONSTRAINT "solicitudes_pkey" PRIMARY KEY (id)
);

CREATE INDEX idx_solicitudes_empresa ON public.solicitudes USING btree (empresa_id);
CREATE INDEX idx_solicitudes_estado ON public.solicitudes USING btree (estado);
CREATE INDEX idx_solicitudes_token ON public.solicitudes USING btree (token);


-- Table: super_administradores
CREATE TABLE public."super_administradores" (
    "id" VARCHAR(55) NOT NULL,
    "usuario" VARCHAR(50) NOT NULL,
    "correo" VARCHAR(100) NOT NULL,
    "contraseña" VARCHAR(255) NOT NULL,
    "nombre" VARCHAR(100) NOT NULL,
    "estado_cuenta" VARCHAR(20) DEFAULT 'activo'::character varying,
    "fecha_registro" TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "super_administradores_pkey" PRIMARY KEY (id),
    CONSTRAINT "super_administradores_usuario_key" UNIQUE (usuario),
    CONSTRAINT "super_administradores_correo_key" UNIQUE (correo)
);



-- Table: system_logs
CREATE TABLE public."system_logs" (
    "id" SERIAL NOT NULL,
    "nivel" VARCHAR(20) NOT NULL,
    "mensaje" TEXT NOT NULL,
    "contexto" JSONB DEFAULT '{}'::jsonb,
    "ruta" VARCHAR(255),
    "fecha" TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "empresa_id" VARCHAR(55),
    CONSTRAINT "system_logs_pkey" PRIMARY KEY (id)
);



-- Table: tolerancias
CREATE TABLE public."tolerancias" (
    "id" VARCHAR(55) NOT NULL,
    "nombre" VARCHAR(55) NOT NULL,
    "permite_registro_anticipado" BOOLEAN DEFAULT true,
    "minutos_anticipado_max" INTEGER DEFAULT 60,
    "aplica_tolerancia_entrada" BOOLEAN DEFAULT true,
    "aplica_tolerancia_salida" BOOLEAN DEFAULT false,
    "dias_aplica" JSON,
    "fecha_registro" TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "es_activo" BOOLEAN DEFAULT true,
    "empresa_id" VARCHAR(55),
    "reglas" JSONB DEFAULT '[]'::jsonb,
    "minutos_anticipo_salida" INTEGER DEFAULT 0,
    "minutos_posterior_salida" INTEGER DEFAULT 60,
    CONSTRAINT "tolerancias_pkey" PRIMARY KEY (id)
);



-- Table: usuarios
CREATE TABLE public."usuarios" (
    "id" VARCHAR(55) NOT NULL,
    "usuario" VARCHAR(50) NOT NULL,
    "correo" VARCHAR(50) NOT NULL,
    "contraseña" TEXT NOT NULL,
    "nombre" TEXT NOT NULL,
    "foto" TEXT,
    "telefono" VARCHAR(10),
    "estado_cuenta" tipo_estado_cuenta DEFAULT 'activo'::tipo_estado_cuenta,
    "es_empleado" BOOLEAN DEFAULT false,
    "fecha_registro" TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "clave_seguridad" INTEGER,
    "empresa_id" VARCHAR(55) NOT NULL,
    "intentos_fallidos" INTEGER DEFAULT 0,
    "bloqueado_hasta" TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT "usuarios_clave_seguridad_key" UNIQUE (clave_seguridad),
    CONSTRAINT "usuarios_usuario_empresa_key" UNIQUE (usuario, empresa_id),
    CONSTRAINT "usuarios_correo_empresa_key" UNIQUE (correo, empresa_id),
    CONSTRAINT "usuarios_pkey" PRIMARY KEY (id)
);

CREATE INDEX idx_usuarios_estado ON public.usuarios USING btree (estado_cuenta);
CREATE INDEX idx_usuarios_es_empleado ON public.usuarios USING btree (es_empleado);


-- Table: usuarios_roles
CREATE TABLE public."usuarios_roles" (
    "id" VARCHAR(55) NOT NULL,
    "fecha_registro" TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "es_activo" BOOLEAN DEFAULT true,
    "usuario_id" VARCHAR(55) NOT NULL,
    "rol_id" VARCHAR(55) NOT NULL,
    CONSTRAINT "usuarios_roles_pkey" PRIMARY KEY (id)
);

CREATE INDEX idx_usuarios_roles_usuario ON public.usuarios_roles USING btree (usuario_id);
CREATE INDEX idx_usuarios_roles_rol ON public.usuarios_roles USING btree (rol_id);
CREATE INDEX idx_usuarios_roles_activo ON public.usuarios_roles USING btree (es_activo);


-- Foreign Key Constraints
ALTER TABLE public."asistencias" ADD CONSTRAINT "fk_asistencias_empleado" FOREIGN KEY (empleado_id) REFERENCES empleados(id) ON DELETE CASCADE;
ALTER TABLE public."asistencias" ADD CONSTRAINT "fk_asistencia_departamento" FOREIGN KEY (departamento_id) REFERENCES departamentos(id);
ALTER TABLE public."asistencias" ADD CONSTRAINT "fk_asistencias_horario" FOREIGN KEY (horario_id) REFERENCES horarios(id) ON DELETE SET NULL;
ALTER TABLE public."asistencias" ADD CONSTRAINT "fk_asistencias_empresa" FOREIGN KEY (empresa_id) REFERENCES empresas(id) ON DELETE CASCADE;
ALTER TABLE public."avisos" ADD CONSTRAINT "fk_avisos_empresa" FOREIGN KEY (empresa_id) REFERENCES empresas(id) ON DELETE CASCADE;
ALTER TABLE public."avisos_empleados" ADD CONSTRAINT "fk_avisos_empleados_empleado" FOREIGN KEY (empleado_id) REFERENCES empleados(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public."avisos_empleados" ADD CONSTRAINT "fk_avisos_empleados_aviso" FOREIGN KEY (aviso_id) REFERENCES avisos(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public."avisos_empleados" ADD CONSTRAINT "avisos_empleados_aviso_id_fkey" FOREIGN KEY (aviso_id) REFERENCES avisos(id) ON DELETE CASCADE;
ALTER TABLE public."biometrico" ADD CONSTRAINT "fk_biometrico_escritorio" FOREIGN KEY (escritorio_id) REFERENCES escritorio(id) ON DELETE SET NULL;
ALTER TABLE public."configuraciones_escritorio" ADD CONSTRAINT "configuraciones_escritorio_configuracion_id_fkey" FOREIGN KEY (configuracion_id) REFERENCES configuraciones(id) ON DELETE CASCADE;
ALTER TABLE public."configuraciones_escritorio" ADD CONSTRAINT "configuraciones_escritorio_escritorio_id_fkey" FOREIGN KEY (escritorio_id) REFERENCES escritorio(id) ON DELETE CASCADE;
ALTER TABLE public."credenciales" ADD CONSTRAINT "fk_credenciales_empleado" FOREIGN KEY (empleado_id) REFERENCES empleados(id) ON DELETE CASCADE;
ALTER TABLE public."departamentos" ADD CONSTRAINT "fk_departamentos_empresa" FOREIGN KEY (empresa_id) REFERENCES empresas(id) ON DELETE CASCADE;
ALTER TABLE public."dias_festivos" ADD CONSTRAINT "fk_dias_festivos_empresa" FOREIGN KEY (empresa_id) REFERENCES empresas(id) ON DELETE CASCADE;
ALTER TABLE public."empleados" ADD CONSTRAINT "fk_empleados_horario" FOREIGN KEY (horario_id) REFERENCES horarios(id) ON DELETE SET NULL;
ALTER TABLE public."empleados" ADD CONSTRAINT "fk_empleados_usuario" FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE;
ALTER TABLE public."empleados_departamentos" ADD CONSTRAINT "fk_empleados_departamentos_empleado" FOREIGN KEY (empleado_id) REFERENCES empleados(id) ON DELETE CASCADE;
ALTER TABLE public."empleados_departamentos" ADD CONSTRAINT "fk_empleados_departamentos_departamento" FOREIGN KEY (departamento_id) REFERENCES departamentos(id) ON DELETE CASCADE;
ALTER TABLE public."empresas" ADD CONSTRAINT "fk_empresas_configuracion" FOREIGN KEY (configuracion_id) REFERENCES configuraciones(id) ON DELETE SET NULL;
ALTER TABLE public."escritorio" ADD CONSTRAINT "fk_escritorio_empresa" FOREIGN KEY (empresa_id) REFERENCES empresas(id) ON DELETE CASCADE;
ALTER TABLE public."eventos" ADD CONSTRAINT "fk_eventos_empleado" FOREIGN KEY (empleado_id) REFERENCES empleados(id) ON DELETE SET NULL;
ALTER TABLE public."eventos" ADD CONSTRAINT "fk_eventos_empresa" FOREIGN KEY (empresa_id) REFERENCES empresas(id) ON DELETE CASCADE;
ALTER TABLE public."horarios" ADD CONSTRAINT "fk_horarios_empresa" FOREIGN KEY (empresa_id) REFERENCES empresas(id) ON DELETE CASCADE;
ALTER TABLE public."incidencias" ADD CONSTRAINT "fk_incidencias_empleado" FOREIGN KEY (empleado_id) REFERENCES empleados(id) ON DELETE CASCADE;
ALTER TABLE public."incidencias" ADD CONSTRAINT "fk_incidencias_empresa" FOREIGN KEY (empresa_id) REFERENCES empresas(id) ON DELETE CASCADE;
ALTER TABLE public."movil" ADD CONSTRAINT "fk_movil_empleado" FOREIGN KEY (empleado_id) REFERENCES empleados(id) ON DELETE CASCADE;
ALTER TABLE public."movil" ADD CONSTRAINT "fk_movil_empresa" FOREIGN KEY (empresa_id) REFERENCES empresas(id) ON DELETE CASCADE;
ALTER TABLE public."permisos_auditoria" ADD CONSTRAINT "fk_permisos_auditoria_rol" FOREIGN KEY (rol_id) REFERENCES roles(id) ON DELETE CASCADE;
ALTER TABLE public."permisos_auditoria" ADD CONSTRAINT "fk_permisos_auditoria_usuario" FOREIGN KEY (usuario_modificador_id) REFERENCES usuarios(id) ON DELETE SET NULL;
ALTER TABLE public."roles" ADD CONSTRAINT "fk_roles_tolerancia" FOREIGN KEY (tolerancia_id) REFERENCES tolerancias(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE public."roles" ADD CONSTRAINT "fk_roles_empresa" FOREIGN KEY (empresa_id) REFERENCES empresas(id) ON DELETE CASCADE;
ALTER TABLE public."solicitudes" ADD CONSTRAINT "fk_solicitudes_empresa" FOREIGN KEY (empresa_id) REFERENCES empresas(id) ON DELETE CASCADE;
ALTER TABLE public."system_logs" ADD CONSTRAINT "system_logs_empresa_id_fkey" FOREIGN KEY (empresa_id) REFERENCES empresas(id) ON DELETE SET NULL;
ALTER TABLE public."tolerancias" ADD CONSTRAINT "fk_tolerancias_empresa" FOREIGN KEY (empresa_id) REFERENCES empresas(id) ON DELETE CASCADE;
ALTER TABLE public."usuarios" ADD CONSTRAINT "fk_usuarios_empresa" FOREIGN KEY (empresa_id) REFERENCES empresas(id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE public."usuarios_roles" ADD CONSTRAINT "fk_usuarios_roles_usuario" FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE;
ALTER TABLE public."usuarios_roles" ADD CONSTRAINT "fk_usuarios_roles_rol" FOREIGN KEY (rol_id) REFERENCES roles(id) ON DELETE CASCADE;